import fs from 'node:fs'
import path from 'node:path'
import { type Flow, type FlowStep, loadFlows } from './flows.js'

/**
 * `.squint/flows/*.flow` → Playwright specs. Flows are squint's
 * lightweight journeys, replayed over CDP every turn; exporting them
 * turns the same six-line scripts into repo-versioned end-to-end tests
 * that run under the e2e gate, in CI, and on the team's machines.
 * Generated files are a starting point — edit freely.
 */

/** HTML tags a bare `click <word>` most plausibly means as a selector. */
const TAGS = new Set([
  'a',
  'button',
  'input',
  'select',
  'textarea',
  'summary',
  'label',
  'form',
  'nav',
  'header',
  'footer',
  'main',
  'section',
  'article',
  'aside',
  'dialog',
  'details',
  'li',
  'ul',
  'ol',
  'img',
  'svg',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'p',
  'span',
  'div',
  'table',
  'tr',
  'td',
  'th',
])

/** Mirrors the CDP runner: try the target as CSS first, else visible text. */
export function isSelectorLike(target: string): boolean {
  const t = target.trim()
  if (/^[#.[]/.test(t)) return true
  if (/[>:[\]=~+*]/.test(t)) return true
  const tokens = t.toLowerCase().split(/\s+/)
  return tokens.every((tok) => TAGS.has(tok))
}

const q = (s: string): string => JSON.stringify(s)

function clickLocator(target: string): string {
  return isSelectorLike(target) ? `page.locator(${q(target)})` : `clickable(page, ${q(target)})`
}

export function stepToPlaywright(step: FlowStep): string {
  switch (step.kind) {
    case 'goto':
      return `await page.goto(${q(step.route)})`
    case 'click':
      return `await ${clickLocator(step.target)}.click()`
    case 'fill':
      return `await page.locator(${q(step.selector)}).fill(${q(step.value)})`
    case 'press':
      return `await page.keyboard.press(${q(step.key)})`
    case 'expect':
      // The CDP runner checks body.innerText, case-insensitively; toContainText with a regex matches that.
      return `await expect(page.locator('body')).toContainText(${regexLiteral(step.text)})`
    case 'shot':
      return `await page.screenshot({ path: test.info().outputPath(${q(`${step.name}.png`)}), fullPage: true })`
    case 'hover':
      return isSelectorLike(step.target)
        ? `await page.locator(${q(step.target)}).hover()`
        : `await page.getByText(${regexLiteral(step.target)}).first().hover()`
    case 'scroll':
      if (step.target === 'bottom') return `await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight))`
      if (step.target === 'top') return `await page.evaluate(() => window.scrollTo(0, 0))`
      return `await page.locator(${q(step.target)}).scrollIntoViewIfNeeded()`
    case 'wait':
      return `await page.waitForTimeout(${step.ms}) // from the flow; prefer a web-first assertion on what you were waiting for`
    case 'budget':
      return `// budget ${step.metric} ${step.ms}ms — a squint metric (soft-navigation ICP); keep it in the .flow, Playwright has no equivalent`
  }
}

function regexLiteral(text: string): string {
  const escaped = text.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')
  return `/${escaped}/i`
}

const usesClickable = (flow: Flow): boolean =>
  flow.steps.some((s) => s.kind === 'click' && !isSelectorLike(s.target))

export function flowToSpec(flow: Flow): string {
  const header = [
    `// Generated by \`squint flows export\` from .squint/flows/${flow.name}.flow — edit freely; regenerate with --force.`,
    `import { expect, test${usesClickable(flow) ? ', type Page' : ''} } from '@playwright/test'`,
    '',
  ]
  if (usesClickable(flow)) {
    header.push(
      '/** The flow runner\'s click semantics: a clickable element whose visible text contains the target (case-insensitive). */',
      'const clickable = (page: Page, text: string) =>',
      "  page.locator('a, button, [role=button], input[type=submit], summary, label', { hasText: text }).first()",
      '',
    )
  }
  const body = flow.steps.map((step) => `  ${stepToPlaywright(step)}`)
  return [...header, `test(${q(flow.name)}, async ({ page }) => {`, ...body, '})', ''].join('\n')
}

export interface ExportResult {
  written: string[]
  skipped: string[]
}

/** Write one spec per flow into `dir` (default tests/e2e); existing files stay unless `force`. */
export function exportFlows(cwd: string, opts: { dir?: string; force?: boolean } = {}): ExportResult {
  const dir = path.join(cwd, opts.dir ?? 'tests/e2e')
  const result: ExportResult = { written: [], skipped: [] }
  const flows = loadFlows(cwd)
  if (flows.length === 0) return result
  fs.mkdirSync(dir, { recursive: true })
  for (const flow of flows) {
    const file = path.join(dir, `${flow.name}.spec.ts`)
    const rel = path.relative(cwd, file)
    if (fs.existsSync(file) && !opts.force) {
      result.skipped.push(rel)
      continue
    }
    fs.writeFileSync(file, flowToSpec(flow))
    result.written.push(rel)
  }
  return result
}
